### ISSUE TITLE
doctrine:phpcr:fixtures:load failed if phpcr_user is defined to be null

### ISSUE THREAD

**Issue by krichprollsch** [symfony-cmf/standard-edition#30]
With the default `parameter.yml` but with `phpcr_user` defined to `null`

```
    phpcr_user: ~ 
```

The command `php app/console doctrine:phpcr:fixtures:load` returns

```
  [PHPCR\NodeType\ConstraintViolationException]
  Can't remove the protected property: jcr:createdBy
```

The source of error is hard to find with this message.
Maybe it will be useful to check `phpcr_user` with not null condition into DoctrinePHPCRBundle ?

**Comment by dbu** [comment]
indeed, seems that we must forbid this configuration from being null. created https://github.com/doctrine/DoctrinePHPCRBundle/issues/182 as it belongs there, not into this repository.

**Comment by krichprollsch** [comment]
thanks
