### ISSUE TITLE
Skip prompt when purging DB

### ISSUE THREAD

**Issue by cadorn** [symfony-cmf/standard-edition#36]
When running:

    php app/console doctrine:database:create
    php app/console doctrine:phpcr:init:dbal
    php app/console doctrine:phpcr:repository:init
    php app/console doctrine:phpcr:fixtures:load

How do I skip the prompt asking if I want to purge the DB? I want to just force a `Y`.

**Comment by dbu** [comment]
you can run the commands with `--help` to see the options. most of them have a `--force` parameter. we are just a bit paranoid about putting them into the tutorial as we do not want the blame if a beginner wipes some database he cared about...
