### ISSUE TITLE
Unable to find the controller for path "/demo/login_check"

### ISSUE THREAD

**Issue by cadorn** [symfony-cmf/standard-edition#38]
I have deployed this to OpenShift and am getting a security error when trying to log in at: http://pinfwiki-cadorn.rhcloud.com/symfony-cmf/web/app_dev.php/demo/login

I presume I need to configure `security.yml`.

I found this one `https://github.com/symfony-cmf/cmf-sandbox/blob/master/app/config/security.yml` but it looks like the structure is different here.

I am all new to the symfony security system and am hoping to get a sample `security.yml` file I can drop in to make the demo work online using `app_dev.php`.

**Comment by dbu** [comment]
this is a hardwired security measure built into [app_dev.php](https://github.com/symfony-cmf/standard-edition/blob/master/web/app_dev.php#L12-L15). you really do not want public users to access app_dev.php as they can see way too many things about your application. if you really do want to develop remotely, you should tunnel your connection through ssh, or if you have a static ip you could allow that ip in your project. for a public site, the recommended thing is to entirely remove app_dev.php during the deployment process.

these things are not cmf specific at all, but the same as the core symfony framework. if you did not yet, i recommend you to read the  [quick tour](http://symfony.com/doc/current/quick_tour/the_big_picture.html) and the first couple of chapters of the [symfony book](http://symfony.com/doc/current/book/index.html). i tried to find a single point where the security in app_dev.php is specifically explained, but did not find that. maybe @WouterJ can point you to something specific.

**Comment by WouterJ** [comment]
in https://github.com/symfony-cmf/standard-edition/pull/54, all these demo stuffs were removed
