### ISSUE TITLE
Unable to select images with hallo editor

### ISSUE THREAD

**Issue by umpirsky** [symfony-cmf/standard-edition#40]
In `src/Acme/DemoBundle/Resources/views/layout.html.twig` I included hallo editor like:

```
{% render(controller("cmf_create.jsloader.controller:includeJSFilesAction", {'editor': 'hallo'})) %}
```

When I try to select image, I get:

![selection_004](https://cloud.githubusercontent.com/assets/208957/7583007/a23f8a9a-f892-11e4-85fc-1b19cdeb998f.png)

Did I miss something?

**Comment by lsmith77** [comment]
it should work in the sandbox. I think what is missing is the ElFinderBundle. we should probably remove the image button in the SE

**Comment by umpirsky** [comment]
Some error in such case would be also helpful.

**Comment by dbu** [comment]
@lsmith77 afaik hallo has nothing to do with elfinder, it has its own image plugin. 

the hallo image plugin might be broken. there is a bunch of [open issues](https://github.com/bergie/hallo/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+image) at the hallo github repository.

the bootstrap code is here:
https://github.com/symfony-cmf/CreateBundle/blob/master/Resources/public/js/init-create-hallo.js#L27-L37

and the image information is triggered here
https://github.com/symfony-cmf/CreateBundle/blob/master/Resources/views/includejsfiles-create.html.twig#L4-L9

but https://github.com/symfony-cmf/CreateBundle/blob/master/DependencyInjection/Configuration.php#L74 looks like by default, image support is disabled. and the standard edition does not change that.

@umpirsky did you change any configuration? if you can investigate the problem, that would be great! i would suggest to first make sure you have the very latest version of hallo - maybe we just need to update the dependency in this bundle.

**Comment by umpirsky** [comment]
@dbu I didn't change anything except described, I will try to dig into it when I find some time. Thanks!

**Comment by dbu** [comment]
thanks! sorry to not be more helpful - i fear the people who did the hallo integration are mostly not active on the project anymore. this is why we switched to ckeditor as default, but its a pitty, hallo is very neat and clean. so any help is appreciated.

**Comment by umpirsky** [comment]
In deed, yes.

**Comment by WouterJ** [comment]
In https://github.com/symfony-cmf/standard-edition/pull/54, all demo stuff was removed from this episode. If this bug is still related, consider opening it on the CreateBundle repository
