### ISSUE TITLE
Can't install v1.3.0-RC1 on PHP 5.5.x - cocur/slugify requires php >=5.6 

### ISSUE THREAD

**Issue by dlancea** [symfony-cmf/standard-edition#51]
Running 
    > composer create-project symfony-cmf/standard-edition symfony-cmf-standard 1.3.0-RC1 -s RC

Results in:

```
Installing symfony-cmf/standard-edition (1.3.0-RC1)
  - Installing symfony-cmf/standard-edition (1.3.0-RC1)
    Loading from cache

Created project in symfony-cmf-standard
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for cocur/slugify v1.4.1 -> satisfiable by cocur/slugify[v1.4.1].
    - cocur/slugify v1.4.1 requires php >=5.6 -> your PHP version (5.5.32) does not satisfy that requirement.
  Problem 2
    - cocur/slugify v1.4.1 requires php >=5.6 -> your PHP version (5.5.32) does not satisfy that requirement.
    - sonata-project/core-bundle 2.3.10 requires cocur/slugify ~1.4 -> satisfiable by cocur/slugify[v1.4.1].
    - Installation request for sonata-project/core-bundle 2.3.10 -> satisfiable by sonata-project/core-bundle[2.3.10].
```

This breaks compatibility with Symfony 2.3.x, which is listed on the readme.

**Comment by WouterJ** [comment]
Hmm, seems like our default lock file is not compatible with PHP 5.3. If you clone this repo locally, you should be able to install all dependencies by running `composer update`. I'll update the lock file for 5.3 support soon.

**Comment by WouterJ** [comment]
I've updated the lock file in master. Can you please try `composer create-project symfony-cmf/standard-edition symfony-cmf-standard dev-master` to see if the new lock file does work correctly? If it does, I'll tag RC2 to fix this issue. Thanks for your report!

**Comment by dlancea** [comment]
Yup, installing dev-master worked.

A minor issue, when I ran create-project, I got this composer warning:

```
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
```

Not a big deal, but might be confusing for newbies.

Thanks for the fix!

**Comment by WouterJ** [comment]
Fixed that warning as well now and tagged a new release: https://github.com/symfony-cmf/standard-edition/releases/tag/1.3.0-RC2

Thanks again for your help!
