### ISSUE TITLE
Unable to find template "AppBundle:Security:login.html.twig". (RC2)

### ISSUE THREAD

**Issue by maity-kgz** [symfony-cmf/standard-edition#52]
In 1.3.RC2 there is error when you navigate to /demo/login

> Unable to find template "AppBundle:Security:login.html.twig".
500 Internal Server Error - InvalidArgumentException
3 linked Exceptions: Twig_Error_Loader » InvalidArgumentException » InvalidArgumentException »

**Comment by WouterJ** [comment]
Thanks for reporting this! In https://github.com/symfony-cmf/standard-edition/pull/54, I removed all demo stuff so this error doesn't occur anymore.
